### ISSUE TITLE
Cannot run Python programs using matplotlib, numpy and scipy

### ISSUE THREAD

**Issue by tigran123** [corbinlc/GNURootDebian#115]
Look at this session log:

```
# cat test.py
from __future__ import print_function
import matplotlib as mplt
mplt.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import scipy.fftpack as fftpack
from scipy.special import hyp1f1

print("Hello, world")

# python3 test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import matplotlib as mplt
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 180, in <module>
    from matplotlib.cbook import is_string_like
  File "/usr/lib/python3/dist-packages/matplotlib/cbook.py", line 33, in <module>
    import numpy as np
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/usr/lib/python3/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python3/dist-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/usr/lib/python3/dist-packages/numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/usr/lib/python3/dist-packages/numpy/linalg/__init__.py", line 50, in <module>
    from .linalg import *
  File "/usr/lib/python3/dist-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: libatlas.so.3: cannot enable executable stack as shared object requires: Permission denied
```

This is on Android 5.1.1 on Nexus10

**Comment by tigran123** [comment]
Interestingly, on Android 6.0.1/aarch64 the program runs fine.

Curiously, the program (the real one, not the hello-world above) runs in GNURoot Debian environment in 13 minutes, whereas exactly the same program on the same hardware in Termux environment runs in 10 minutes. Other than performance, the advantage of Termux is that I can just run tsu to become real root (uses /system/xbin/su) whereas in GNURoot Debian this does not seem possible at the moment (and as a result, things like ping/traceroute/tcpdump would never work, but in Termux they all work just fine).

However, the key (and very important) advantage of GNURoot Debian (compared to Termux) is the X11 environment. So, I don't give up and will try to get these things to work :)

**Comment by tigran123** [comment]
Also, some more information: I encountered the same problem ("Cannot enable executable stack as shared object requires: Permission denied") also under Android 6.0.1 (on UMI Super aarch64) but there I sorted it out by logging in via adb as root and changing selinux policy to Permissive. Then these errors disappeared and I could run mplayer and mpv to play movies (well, mplayer worked, but mpv failed for some unrelated reasons).

**Comment by steve-j-wilcox** [comment]
I'm trying to install jupyter/matplotlib/scipy/... but run into a permissions error. Have also tried this in termuc but whilst I can install jupyter and it works I can't install scipy/matplotlib how did you manage to get them running??

**Comment by AdamMatthewLTM** [comment]
Hi all,

Thank you for your input in these matters.

I am attempting to assist the developers in sorting out issues for GNU Root Debian on GitHub. Tigran123 , could you please let me know if you are still having difficulties with running python scripts?

Also, if there are any issues that you would consider to be high priority that are not already listed, could you please create a new post on GitHub and I will sort it ASAP?

Thank you for your time and patience,
-Adam

**Comment by tigran123** [comment]
@AdamMatthewLTM Thank you, brother. Let's work on these. Now, concerning python: this is no longer an issue because: a) both the latest python interpreter (3.6.5) and all the modules compile and run perfectly on Termux and b) there are too many issues with python on GNURoot Debian --- just try to compile python 3.6.5 with "--enable-optimizations" and the self-tests will fail.

So, instead of sorting out python issues let's try to sort out #253 --- this is actually "mission-critical", because GNURoot Debian allows to do something impossible in Termux: run binaries compiled for other Debian systems. I'll be open and specific: GNURoot Debian is the only thing in existence that allows to run Wolfram Mathematica 11.2 binaries compiled and shipped (with free license) on Raspberry Pi as part of Raspbian, thus bringing this powerful program to every Android phone, tablet etc. The GUI frontend (mathematica) doesn't work because it is compiled for Debian Stretch and even if we take the earlier (10.2) version which is compiled for Debian Jessie it will not start because (presumably) of ptrace() emulation in proot, i.e. htop shows the proot and mathematica processes in 't' (traced) state and this goes on forever (I waited 5 days and it never completed). So, running GUI is, unfortunately, impossible. But the terminal-based "math" (or "wolfram") command works perfectly and with minimal precautions (e.g. instead of LaunchKernels[N] one has to do Needs["SubKernels`RemoteKernels`"];
LaunchKernels[RemoteMachine["localhost", N]]) it works beautifully. But on mobiles with small amount of internal storage you can't fit both the application (1G) and the paclet repositories (potentially infinite, though 15GB space ought to be enough) in the internal storage. And placing them on the micro sd makes them inaccessible because Wolfram assumes that if you can't cd somewhere, then that "somewhere" is not accessible.

**Comment by tigran123** [comment]
@steve-j-wilcox Steve, in order to add numpy, scipy etc you need to enable its-pointless' repository as described here:

[https://wiki.termux.com/wiki/Package_Management#its-pointless_.28live_the_dream.29](https://wiki.termux.com/wiki/Package_Management#its-pointless_.28live_the_dream.29)
