### ISSUE TITLE
Exception 

### ISSUE THREAD

**Issue by avishaybennatan** [corbinlc/GNURootDebian#189]
Hello
tried to compile and run it on Android 5.1 ICube X86 tablet
[exception.txt](https://github.com/corbinlc/GNURootDebian/files/1117994/exception.txt)

thanks in advance.

**Comment by avishaybennatan** [comment]
The same issue is present when using the original binaries
9566): java.io.FileNotFoundException: images
07-02 11:19:30.960 E/tag     ( 9566): 	at android.content.res.AssetManager.openAsset(Native Method)
07-02 11:19:30.960 E/tag     ( 9566): 	at android.content.res.AssetManager.open(AssetManager.java:313)
07-02 11:19:30.960 E/tag     ( 9566): 	at android.content.res.AssetManager.open(AssetManager.java:287)
07-02 11:19:30.960 E/tag     ( 9566): 	at com.gnuroot.debian.GNURootMain.copyAssets(GNURootMain.java:567)
07-02 11:19:30.960 E/tag     ( 9566): 	at com.gnuroot.debian.GNURootMain.setupSupportFiles(GNURootMain.java:282)
07-02 11:19:30.960 E/tag     ( 9566): 	at com.gnuroot.debian.GNURootMain.handleIntent(GNURootMain.java:104)
07-02 11:19:30.960 E/tag     ( 9566): 	at com.gnuroot.debian.GNURootMain.onCreate(GNURootMain.java:90)
07-02 11:19:30.960 E/tag     ( 9566): 	at android.app.Activity.performCreate(Activity.java:5990)
07-02 11:19:30.960 E/tag     ( 9566): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
07-02 11:19:30.960 E/tag     ( 9566): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
07-02 11:19:30.960 E/tag     ( 9566): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
07-02 11:19:30.960 E/tag     ( 9566): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
07-02 11:19:30.960 E/tag     ( 9566): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
07-02 11:19:30.960 E/tag     ( 9566): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-02 11:19:30.960 E/tag     ( 9566): 	at android.os.Looper.loop(Looper.java:135)
07-02 11:19:30.960 E/tag     ( 9566): 	at android.app.ActivityThread.main(ActivityThread.java:5258)
07-02 11:19:30.960 E/tag     ( 9566): 	at java.lang.reflect.Method.invoke(Native Method)
07-02 11:19:30.960 E/tag     ( 9566): 	at java.lang.reflect.Method.invoke(Method.java:372)
07-02 11:19:30.960 E/tag     ( 9566): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
07-02 11:19:30.960 E/tag     ( 9566): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
07-02 11:19:30.978 E/TinyAlsaStream( 2497): getFramesAvailable: Unable to get available frames
07-02 11:19:30.978 E/TinyAlsaStream( 2497): getFramesAvailable: Unable to get available frames
07-02 11:19:30.978 E/TinyAlsaStream( 2497): getFramesAvailable: Unable to get available frames
07-02 11:19:31.148 E/MMGR_CLI( 2516): fancy enter mmgr_cli_connect
07-02 11:19:31.148 E/MMGR_CNX( 2516):  socket_open_client - failed to open socket (mmgr)
07-02 11:19:31.148 E/MMGR_CLI( 2516): fancy, enter cli_connect
07-02 11:19:31.148 E/MMGR_CLI( 2516): cli_connect - (fd:-1 name:gnssd) - failed to open socket
07-02 11:19:31.148 E/MMGR_CLI( 2516): fancy, handle_disconnection
07-02 11:19:31.189 E/tag     ( 9566): Failed to copy asset file: sounds
07-02 11:19:31.189 E/tag     ( 9566): java.io.FileNotFoundException: sounds
07-02 11:19:31.189 E/tag     ( 9566): 	at android.content.res.AssetManager.openAsset(Native Method)
07-02 11:19:31.189 E/tag     ( 9566): 	at android.content.res.AssetManager.open(AssetManager.java:313)
07-02 11:19:31.189 E/tag     ( 9566): 	at android.content.res.AssetManager.open(AssetManager.java:287)
07-02 11:19:31.189 E/tag     ( 9566): 	at com.gnuroot.debian.GNURootMain.copyAssets(GNURootMain.java:567)
07-02 11:19:31.189 E/tag     ( 9566): 	at com.gnuroot.debian.GNURootMain.setupSupportFiles(GNURootMain.java:282)
07-02 11:19:31.189 E/tag     ( 9566): 	at com.gnuroot.debian.GNURootMain.handleIntent(GNURootMain.java:104)
07-02 11:19:31.189 E/tag     ( 9566): 	at com.gnuroot.debian.GNURootMain.onCreate(GNURootMain.java:90)
07-02 11:19:31.189 E/tag     ( 9566): 	at android.app.Activity.performCreate(Activity.java:5990)
07-02 11:19:31.189 E/tag     ( 9566): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
07-02 11:19:31.189 E/tag     ( 9566): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
07-02 11:19:31.189 E/tag     ( 9566): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
07-02 11:19:31.189 E/tag     ( 9566): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
07-02 11:19:31.189 E/tag     ( 9566): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
07-02 11:19:31.189 E/tag     ( 9566): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-02 11:19:31.189 E/tag     ( 9566): 	at android.os.Looper.loop(Looper.java:135)
07-02 11:19:31.189 E/tag     ( 9566): 	at android.app.ActivityThread.main(ActivityThread.java:5258)
07-02 11:19:31.189 E/tag     ( 9566): 	at java.lang.reflect.Method.invoke(Native Method)
07-02 11:19:31.189 E/tag     ( 9566): 	at java.lang.reflect.Method.invoke(Method.java:372)
07-02 11:19:31.189 E/tag     ( 9566): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
07-02 11:19:31.189 E/tag     ( 9566): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
07-02 11:19:31.218 E/tag     ( 9566): Failed to copy asset file: webkit
07-02 11:19:31.218 E/tag     ( 9566): java.io.FileNotFoundException: webkit
07-02 11:19:31.218 E/tag     ( 9566): 	at android.content.res.AssetManager.openAsset(Native Method)
07-02 11:19:31.218 E/tag     ( 9566): 	at android.content.res.AssetManager.open(AssetManager.java:313)
07-02 11:19:31.218 E/tag     ( 9566): 	at android.content.res.AssetManager.open(AssetManager.java:287)
07-02 11:19:31.218 E/tag     ( 9566): 	at com.gnuroot.debian.GNURootMain.copyAssets(GNURootMain.java:567)
07-02 11:19:31.218 E/tag     ( 9566): 	at com.gnuroot.debian.GNURootMain.setupSupportFiles(GNURootMain.java:282)
07-02 11:19:31.218 E/tag     ( 9566): 	at com.gnuroot.debian.GNURootMain.handleIntent(GNURootMain.java:104)
07-02 11:19:31.218 E/tag     ( 9566): 	at com.gnuroot.debian.GNURootMain.onCreate(GNURootMain.java:90)
07-02 11:19:31.218 E/tag     ( 9566): 	at android.app.Activity.performCreate(Activity.java:5990)
07-02 11:19:31.218 E/tag     ( 9566): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
07-02 11:19:31.218 E/tag     ( 9566): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
07-02 11:19:31.218 E/tag     ( 9566): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
07-02 11:19:31.218 E/tag     ( 9566): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
07-02 11:19:31.218 E/tag     ( 9566): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
07-02 11:19:31.218 E/tag     ( 9566): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-02 11:19:31.218 E/tag     ( 9566): 	at android.os.Looper.loop(Looper.java:135)
07-02 11:19:31.218 E/tag     ( 9566): 	at android.app.ActivityThread.main(ActivityThread.java:5258)
07-02 11:19:31.218 E/tag     ( 9566): 	at java.lang.reflect.Method.invoke(Native Method)
07-02 11:19:31.218 E/tag     ( 9566): 	at java.lang.reflect.Method.invoke(Method.java:372)
07-02 11:19:31.218 E/tag     ( 9566): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
07-02 11:19:31.218 E/tag     ( 9566): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
07-02 11:19:31.563 E/LicenseChecker( 9566): Could not bind to service.
07-02 11:19:31.727 E/WifiStateMachine( 2826): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.53 rxSuccessRate=0.53 targetRoamBSSID=14:91:82:32:85:8d RSSI=-52
07-02 11:19:31.727 E/WifiStateMachine( 2826): WifiStateMachine starting scan for "Home"WPA_PSK with 2412
07-02 11:19:32.150 E/MMGR_CLI( 2516): fancy enter mmgr_cli_connect
07-02 11:19:32.151 E/MMGR_CNX( 2516):  socket_open_client - failed to open socket (mmgr)
07-02 11:19:32.151 E/MMGR_CLI( 2516): fancy, enter cli_connect
07-02 11:19:32.151 E/MMGR_CLI( 2516): cli_connect - (fd:-1 name:gnssd) - failed to open socket
07-02 11:19:32.151 E/MMGR_CLI( 2516): fancy, handle_disconnection
07-02 11:19:32.598 E/AndroidRuntime( 9566): FATAL EXCEPTION: main
07-02 11:19:32.598 E/AndroidRuntime( 9566): Process: com.gnuroot.debian, PID: 9566
07-02 11:19:32.598 E/AndroidRuntime( 9566): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { cat=[android.intent.category.DEFAULT] flg=0x800000 cmp=com.gnuroot.debian/.GNURootDownloaderActivity }} to activity {com.gnuroot.debian/com.gnuroot.debian.GNURootMain}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ProgressDialog.dismiss()' on a null object reference
07-02 11:19:32.598 E/AndroidRuntime( 9566): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3574)
07-02 11:19:32.598 E/AndroidRuntime( 9566): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617)
07-02 11:19:32.598 E/AndroidRuntime( 9566): 	at android.app.ActivityThread.access$1300(ActivityThread.java:151)
07-02 11:19:32.598 E/AndroidRuntime( 9566): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
07-02 11:19:32.598 E/AndroidRuntime( 9566): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-02 11:19:32.598 E/AndroidRuntime( 9566): 	at android.os.Looper.loop(Looper.java:135)
07-02 11:19:32.598 E/AndroidRuntime( 9566): 	at android.app.ActivityThread.main(ActivityThread.java:5258)
07-02 11:19:32.598 E/AndroidRuntime( 9566): 	at java.lang.reflect.Method.invoke(Native Method)
07-02 11:19:32.598 E/AndroidRuntime( 9566): 	at java.lang.reflect.Method.invoke(Method.java:372)
07-02 11:19:32.598 E/AndroidRuntime( 9566): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
07-02 11:19:32.598 E/AndroidRuntime( 9566): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
07-02 11:19:32.598 E/AndroidRuntime( 9566): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ProgressDialog.dismiss()' on a null object reference
07-02 11:19:32.598 E/AndroidRuntime( 9566): 	at com.gnuroot.debian.GNURootMain.onActivityResult(GNURootMain.java:348)
07-02 11:19:32.598 E/AndroidRuntime( 9566): 	at android.app.Activity.dispatchActivityResult(Activity.java:6192)
07-02 11:19:32.598 E/AndroidRuntime( 9566): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
07-02 11:19:32.598 E/AndroidRuntime( 9566): 	... 10 more

**Comment by AdamMatthewLTM** [comment]
Hi all,

I am currently assisting the developers in sorting relevant issues for GNURoot Debian on GitHub. If the issue discussed is still relevant, could you please reply to this thread and state the issue needs to be resolved and I will attempt to sort it for you ASAP. If the issue is no longer relevant, please reply to this thread and state it has been resolved, and I will suggest this thread be closed.

Furthermore, if a particular issue is considered to be high priority, please state that you are requesting it to be considered as high priority and I will mark it as such.

Thank you all so much for your time and understanding,
-Adam
